- name: packages installing using loop
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}""
      state: latest
    loops:
    - mysql
    - nginx
    - postfix